### ISSUE TITLE
Testing TODO

### ISSUE THREAD

**Issue by abdo1819** [Leon-OnlineLearning/leon-ClientSide#6]
- [x] implement questions view
    - [x] multi choice
    - [x] single choice
    - [x] short/long answers
    - [x] code 
    - [x] image upload
- [x] question creator
    - [x] multi-choice
    - [x] text question
- [x] authentication page
- [ ] exam info
- [x] timer
- [ ] prevent copying
- [ ] prevent going out of focus
- [x] record the exam
