### ISSUE TITLE
Professor TODO

### ISSUE THREAD

**Issue by ak-seyam** [Leon-OnlineLearning/leon-ClientSide#9]
# Professor TODO
- [x] implement events as in documentation
- [x] implement year selector
- [x] implement edit lectures and delete lectures views
- [x] add sign-out  
- [ ] adding functionality
- [ ] adding exams when it get finished
- [ ] organize files and folders with @abdo1819
